# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condensed_urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condensedurl',
            name='visited_count',
            field=models.IntegerField(default=0),
        ),
    ]
